### ISSUE TITLE
ClassTable Inheritance

### ISSUE THREAD

**Issue by rufinus** [K-Phoen/DoctrineStateMachineBehavior#8]
I have a BaseClass `Company` and from it, there is a ClassTable Inheritance to `Supplier`
If i set an state_machine on the Company Class it throws an exception (undefinied index for the Supplier Class).
So i have to use a state_machine for each Inheritated class even if they share the same state maschine.

is there some way around it?

see https://github.com/K-Phoen/DoctrineStateMachineBehavior/blob/master/src/KPhoen/DoctrineStateMachineBehavior/Listener/PersistenceListener.php#L52

Its only checking the class of the entity, but not an eventual present parent class.

**Comment by gl005** [comment]
i submitted a PR solving this issue:
https://github.com/K-Phoen/DoctrineStateMachineBehavior/pull/9

**Comment by K-Phoen** [comment]
Fixed by #9
